# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd9c62cce424a0d452acfe5b270e62e74904ac99b6166027a09e9fd6871184ba14eea144c64b96f79d6975fdfc8f83b5ffa92cded031a2968ca939001081aaa

test:
  secret_key_base: f7e6ec2b326475cd2f9b3984e8442dbd1d1790dfac15c7f1ff54f538534bc97ffa5d913792dd64706284633c785909136da92b19b44cf98516794bde8bfb45f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
